### PR TITLE
Remove assets from generated packages

### PR DESCRIPTION
**Pull request by ruflin**
The registry so far contained generated packages. These packages contained all the same assets and were mainly designed to test the overview page of the package manager. But this now caused problems as many dashboards for example had the same ids. Because of this, all the assets are removed from these example packages and only the package with the icons are now left which is enough to show a nice home screen.

### CODE REVIEW

**Comment by jfsiii** [comment]
The tradeoff is that this removes the data which drives:

- the assets sidebar on the right column of the details page
Screen Shot 2019-10-21 at 9 08 46 AM

- the assets "panel" in the details page

Screen Shot 2019-10-21 at 9 08 58 AM

**Comment by ruflin** [comment]
Correct, but we still have packages which contain all the assets (and real assets) here: https://github.com/elastic/integrations-registry/tree/master/dev/package-examples Happy to add more here.

**Comment by jfsiii** [comment]
> we still have packages which contain all the assets (and real assets) here: https://github.com/elastic/integrations-registry/tree/master/dev/package-examples 

Ah, ok. That's `auditd`, `coredns`, and `iptables` for now. I just took a look and they have a greater breadth of asset types than the set the others were sharing.

> Happy to add more here

I believe we are missing examples with ILM policies and rollup jobs, but I will confirm and get back to you

**Comment by ruflin** [comment]
@jfsiii Correct. But rollups will not be part of MVP AFAIK.

**Pull request merged**
